config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resources :stores
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  belongs_to :store
  scope :by_store, -> (store) { where(store_id: store) }

  def available_payment_methods
    @available_payment_methods ||= Spree::PaymentMethod.available(:front_end, store)
  end
end

app/models/spree/payment_method_decorator.rb
Spree::PaymentMethod.class_eval do
  has_many :store_payment_methods
  has_many :stores, through: :store_payment_methods

  def self.available(display_on = 'both', store = nil)
    result = all.select do |payment_method|
      payment_method.active &&
        (store.nil? || store.payment_methods.empty? || store.payment_methods.include?(payment_method)) &&
        (payment_method.display_on.blank? || payment_method.display_on.in?(['both', display_on.to_s]))
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_and_belongs_to_many :stores, join_table: 'spree_products_stores'
  scope :by_store, -> (store) { joins(:stores).where(spree_products_stores: { store_id: store }) }
end

app/models/spree/promotion/rules/store.rb
module Spree
  class Promotion
    module Rules
      class Store < PromotionRule
        has_and_belongs_to_many :stores, :class_name => 'Spree::Store', :join_table => 'spree_promotion_rules_stores', :foreign_key => 'promotion_rule_id'

        def eligible?(order, options = {})
          stores.none? or stores.include?(order.store)
        end

        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def store_ids_string
          store_ids.join(',')
        end

        def store_ids_string=(s)
          self.store_ids = s.to_s.split(',').map(&:strip)
        end

      end
    end
  end
end

app/models/spree/shipping_method_decorator.rb
Spree::ShippingMethod.class_eval do
  has_many :store_shipping_methods
  has_many :stores, through: :store_shipping_methods

  # This adds store_match to the list of requirements.
  # This will need to be fixed for Spree 2.0 when split shipments is added
  def available_to_order?(order, display_on= nil)
    available?(order, display_on) &&
    within_zone?(order) &&
    category_match?(order) &&
    currency_match?(order) &&
    store_match?(order)
  end

  def store_match?(order)
    order.store.shipping_methods.empty? || stores.include?(order.store)
  end
end

app/models/spree/store_decorator.rb
module Spree
  Store.class_eval do
    has_and_belongs_to_many :products, join_table: 'spree_products_stores'
    has_many :taxonomies
    has_many :orders

    has_many :store_payment_methods
    has_many :payment_methods, through: :store_payment_methods

    has_many :store_shipping_methods
    has_many :shipping_methods, through: :store_shipping_methods

    has_and_belongs_to_many :promotion_rules, class_name: 'Spree::Promotion::Rules::Store', join_table: 'spree_promotion_rules_stores', association_foreign_key: 'promotion_rule_id'

    has_attached_file :logo,
      styles: { mini: '48x48>', small: '100x100>', medium: '250x250>' },
      default_style: :medium,
      url: '/spree/store_logos/:id/:style/:basename.:extension',
      path: ':rails_root/public/spree/store_logos/:id/:style/:basename.:extension',
      convert_options: { all: '-strip -auto-orient' }

    if respond_to? :logo_file_name
      validates_attachment_file_name :logo, matches: [/png\Z/i, /jpe?g\Z/i]
    end

  end
end

app/models/spree/store_payment_method.rb
module Spree
  class StorePaymentMethod < ActiveRecord::Base
    belongs_to :store
    belongs_to :payment_method
  end
end

app/models/spree/store_shipping_method.rb
module Spree
  class StoreShippingMethod < ActiveRecord::Base
    belongs_to :store
    belongs_to :shipping_method
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  scope :by_store, -> (store) { joins(:taxonomy).merge(Spree::Taxonomy.by_store(store)) }

  def self.find_by_store_id_and_permalink!(store_id, permalink)
    by_store(store_id).where(permalink: permalink).first!
  end
end

app/models/spree/taxonomy_decorator.rb
Spree::Taxonomy.class_eval do
  belongs_to :store

  scope :by_store, -> (store) { where(store_id: store) }
end

app/models/spree/tracker_decorator.rb
Spree::Tracker.class_eval do
  belongs_to :store

  def self.current(domain)
    Spree::Tracker.where(active: true).joins(:store).where("spree_stores.url LIKE ?", "%#{domain}%").first
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do
  #update.before :set_stores

  private

  def set_stores
    @product.store_ids = nil unless params[:product].key? :store_ids
  end
end

module ProductsControllerExtension
  def update
    store_ids = params[:product][:store_ids]
    if store_ids.present?
      params[:product][:store_ids] = store_ids.split(',')
    end
    super
  end
end

Spree::Admin::ProductsController.prepend ProductsControllerExtension

app/controllers/spree/admin/stores_controller.rb
class Spree::Admin::StoresController < Spree::Admin::ResourceController

  before_filter :load_payment_methods
  before_filter :load_shipping_methods

  def index
    @stores = @stores.ransack({ name_or_domains_or_code_cont: params[:q] }).result if params[:q]
    @stores = @stores.where(id: params[:ids].split(',')) if params[:ids]

    respond_with(@stores) do |format|
      format.html
      format.json
    end
  end

  private
    def load_payment_methods
      @payment_methods = Spree::PaymentMethod.all
    end

    def load_shipping_methods
      @shipping_methods = Spree::ShippingMethod.all
    end
end

app/controllers/spree/home_controller_decorator.rb
Spree::HomeController.class_eval do
  def index
    @searcher = build_searcher(params)
    @products = @searcher.retrieve_products
    @taxonomies = get_taxonomies
  end
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do

  before_filter :can_show_product, only: :show

  private

  def can_show_product
    @product ||= Spree::Product.friendly.find(params[:id])
    if @product.stores.empty? || !@product.stores.include?(current_store)
      raise ActiveRecord::RecordNotFound
    end
  end
end

app/controllers/spree/taxons_controller_decorator.rb
Spree::TaxonsController.class_eval do
   def show
    @taxon = Spree::Taxon.find_by_store_id_and_permalink!(current_store.id, params[:id])
    return unless @taxon

    @searcher = build_searcher(params.merge(taxon: @taxon.id))
    @products = @searcher.retrieve_products
    @taxonomies = get_taxonomies
  end
end

app/helpers/spree/products_helper_decorator.rb
module Spree
  module Api
    ProductsHelper.class_eval do
      def get_taxonomies
        @taxonomies ||= current_store.present? ? Spree::Taxonomy.by_store(current_store) : Spree::Taxonomy
        @taxonomies = @taxonomies.includes(root: :children)
        @taxonomies
      end
    end
  end
end

app/views/spree/admin/products/_index_headers.html.erb
<th><%= Spree.t(:stores) %></th>

app/views/spree/admin/products/_index_rows.html.erb
<td><%= product.stores.map(&:code).join(", ") unless product.stores.empty? %></td>

app/views/spree/admin/products/_index_search_fields.html.erb
<p>
  <label><%= Spree.t(:store) %></label><br />
  <%= f.select :stores_id_eq, Spree::Store.all.collect {|s| [s.name, s.id ] }, {include_blank: true} %></p>
</p>

app/views/spree/admin/products/_stores.html.erb
<p data-hook="admin_product_form_stores" class="omega two columns">
  <%= f.field_container :stores, class: ['form-group'] do %>
    <%= f.label :store_ids, Spree.t(:stores) %>
    <% if can? :modify, Spree::Store %>
      <%= f.hidden_field :store_ids, value: @product.store_ids.join(',') %>
    <% elsif @product.stores.any? %>
      <ul class="text_list">
        <% @product.stores.each do |store| %>
          <li><%= store.name %></li>
        <% end %>
      </ul>
    <% else %>
      <div class="alert alert-info">
        <%= Spree.t(:no_resource_found, resource: :stores) %>
      </div>
    <% end %>
  <% end %>
</p>

<script type="text/javascript" charset="utf-8">
  Spree.routes.store_search = '<%= spree.admin_stores_path(format: :json) %>';
  $('#product_store_ids').storeAutocomplete();
</script>

app/views/spree/admin/promotions/rules/_store.html.erb
<div class="field alpha omega eight columns">
  <label><%= Spree.t('store_rule.choose_stores') %></label><br>
  <input type='hidden' name='<%= param_prefix %>[store_ids_string]' class='store_picker fullwidth' value='<%= promotion_rule.store_ids.join(",") %>'>
</div>
<script>
  Spree.routes.store_search = '<%= spree.admin_stores_path(format: :json) %>';
  $('.store_picker').storeAutocomplete();
</script>

app/views/spree/admin/stores/_form.html.erb
<div class="row">
  <div data-hook="stores">
    <div data-hook="admin_store_form_fields_left" class="col-md-6">

      <div data-hook="name">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, Spree.t(:store_name) %><br />
          <%= f.text_field :name, class: 'form-control' %>
          <%= error_message_on :store, :name %>
        <% end %>
      </div>

      <div data-hook="code">
        <%= f.field_container :code, class: ['form-group'] do %>
          <%= f.label :code, Spree.t(:store_code) %><br />
          <%= f.text_field :code, class: 'form-control' %>
          <%= error_message_on :store, :code %>
        <% end %>
      </div>

      <div data-hook="default" class="form-group">
        <strong><%= Spree.t(:default) %></strong>

        <div class="radio">
          <%= f.label :default, Spree.t(:default) do %>
            <%= f.radio_button :default, "true" %>
            <%= Spree.t(:say_yes) %>
          <% end %>
          <%= f.label :default, Spree.t(:default) do %>
            <%= f.radio_button :default, "false" %>
            <%= Spree.t(:say_no) %>
          <% end %>
        </div>
      </div>

      <div data-hook="mail_form_address">
        <%= f.field_container :mail_from_address, class: ['form-group'] do %>
          <%= f.label :mail_from_address, Spree.t(:send_mails_as) %><br />
          <%= f.text_field :mail_from_address, class: 'form-control' %>
          <%= error_message_on :store, :mail_from_address %>
        <% end %>
      </div>

      <div data-hook="url">
        <%= f.field_container :url, class: ['form-group'] do %>
          <%= f.label :url, Spree.t(:domains) %><br />
          <%= f.text_area :url, cols: 60, rows: 4, class: 'form-control' %>
          <%= error_message_on :store, :url %>
        <% end %>
      </div>
    </div>

    <div data-hook="admin_store_form_fields_right" class="col-md-6">
      <div data-hook="logo">
        <%= image_tag @store.logo %>
        <%= f.field_container :logo, class: ['form-group'] do %>
          <%= f.label :logo, Spree.t(:logo) %><br />
          <%= f.file_field :logo %>
          <%= error_message_on :store, :logo %>
        <% end %>
      </div>

      <div data-hook="payment_methods">
        <%= f.field_container :payment_methods, class: ['form-group'] do %>
          <%= f.label :payment_methods, Spree.t(:payment_methods) %><br />
          <% @payment_methods.each do |payment_method| %>
            <label class="sub">
              <%= check_box_tag 'store[payment_method_ids][]', payment_method.id, @store.payment_methods.include?(payment_method) %>
            </label> &nbsp;
            <!-- "#{payment_method.name} (#{payment_method.environment})" -->
            <%= payment_method.name %>
            <br>
          <% end %>
          <%= hidden_field_tag 'store[payment_method_ids][]', '' %>
        <% end %>
      </div>

      <div data-hook="shipping_methods">
        <%= f.field_container :shipping_methods, class: ['form-group'] do %>
          <%= f.label :shipping_methods, Spree.t(:shipping_methods) %><br />
          <% @shipping_methods.each do |shipping_method| %>
            <label class="sub">
              <%= check_box_tag 'store[shipping_method_ids][]', shipping_method.id, @store.shipping_methods.include?(shipping_method) %>
            </label> &nbsp;
            <%= shipping_method.name %>
            <br>
          <% end %>
          <%= hidden_field_tag 'store[shipping_method_ids][]', '' %>
        <% end %>
      </div>

      <div data-hook="default_currency">
        <%= f.field_container :default_currency, class: ['form-group'] do %>
          <%= f.label :default_currency, Spree.t(:default_currency) %>
          <%= f.text_field :default_currency, class: 'form-control' %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/spree/admin/stores/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_store) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_stores_list), spree.admin_stores_path, class: 'btn-primary', icon: 'arrow-left' %>
<% end %>

<div data-hook="admin_store_edit_form_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @store } %>
</div>

<div data-hook="admin_store_edit_form">
  <%= form_for [:admin, @store], html: { multipart: true } do |f| %>
    <fieldset class="no-border-top">
      <%= render partial: 'form', locals: { f: f } %>
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </fieldset>
  <% end %>
</div>

app/views/spree/admin/stores/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:stores) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_store), new_object_url, class: 'btn-success', icon: 'add', id: 'admin_new_store_link' %>
<% end %>

<table class="table index" id='listing_stores'>
  <colgroup>
    <col style="width: 20px">
    <col style="width: 120px">
    <col style="width: 80px">
    <col style="width: 80px">
    <col style="width: 220px">
    <col style="width: 15%">
    <col style="width: 15%">
  </colgroup>
  <thead>
  <th><%= Spree.t(:default) %></th>
  <th><%= Spree.t(:store_name) %></th>
  <th><%= Spree.t(:store_code) %></th>
  <th><%= Spree.t(:send_mails_as) %></th>
  <th><%= Spree.t(:domains) %></th>
  <th data-hook="admin_stores_index_header_actions" class="actions"></th>
  </thead>
  <tbody>
  <% @stores.each do |store|%>
    <tr id="<%= spree_dom_id store %>"
        data-hook="admin_stores_index_rows" class="<%= cycle('odd', 'even') %>">
      <td><%= store.default %></td>
      <td><%= store.name %></td>
      <td><%= store.code %></td>
      <td><%= store.mail_from_address %></td>
      <td><%= store.url %></td>
      <td data-hook="admin_stores_index_row_actions" class="actions">
        <%= link_to_edit store, no_text: true %> &nbsp;
        <%= link_to_delete store, no_text: true %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/stores/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_store) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_stores_list), spree.admin_stores_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<div data-hook="admin_store_new_form_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @store } %>
</div>

<div data-hook="admin_store_new_form">
  <%= form_for [:admin, @store], html: {multipart: true}  do |f| %>
    <fieldset class="no-border-top">
      <%= render partial: 'form', locals: { f: f } %>
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </fieldset>
  <% end %>
</div>

app/views/spree/admin/taxonomies/_store.html.erb
<%= f.field_container :store_id, class: ['form-group'] do %>
  <%= f.label :name, Spree.t(:store) %> <span class="required">*</span>
  <%= f.collection_select(:store_id, Spree::Store.all, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
<% end %>

app/views/spree/admin/trackers/_index_rows.html.erb
<td><%= tracker.store.name %></td>

app/views/spree/admin/trackers/_store.html.erb
<div class="col-md-4">
  <div data-hook="store" class="form-group">
    <label><%=t("store")%></label>
    <span>
      <%= collection_select(:tracker, :store_id, Spree::Store.all, :id, :name, {}, {class: 'select2'}) %>
    </span>
  </div>
</div>

app/views/spree/products/_taxons.html.erb
<% if (product_taxons_by_store = @product.taxons.by_store(current_store)).present? %>
  <h3 class="product-section-title"><%= Spree.t(:look_for_similar_items) %></h3>
  <ul class="list-group" id="similar_items_by_taxon" data-hook>
    <% product_taxons_by_store.each do |taxon| %>
      <li class="list-group-item"><%= link_to taxon.name, seo_url(taxon) %></li>
    <% end %>
  </ul>
<% end %>

app/views/spree/shared/_google_analytics.js.erb
<% if tracker = current_tracker %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    <% if user_analytics_id = try_spree_current_user.try(:analytics_id) %>
      ga('create', { 'trackingId': '<%= tracker.analytics_id %>', 'cookieDomain': 'auto', 'userId': '<%= user_analytics_id %>' });
    <% else %>
      ga('create', '<%= tracker.analytics_id %>', 'auto');
    <% end %>

    ga('require', 'displayfeatures');
    <%= yield :google_analytics %>
    ga('send', 'pageview');
  </script>
<% end %>